version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: springboot-security-jwt
      POSTGRES_USER: springboot
      POSTGRES_PASSWORD: springboot
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  postgres-data:

networks:
  springboot-network:
