
services:
  springboot-jpa-db:
    image: mysql:latest
    container_name: springboot-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Change this to your desired root password
      MYSQL_DATABASE: db_backend_products
      MYSQL_USER: springboot
      MYSQL_PASSWORD: springboot
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data

volumes:
  mysql-data: